### ISSUE TITLE
Unrelated

### ISSUE THREAD

**Issue by abernatskiy** [TheNode92/Node-Kurulum-Santiment#1]
Hello @TheNode92 ! Unrelated to this repo, but I needed to contact you.

I'm one of the judges for Subsquid migration quests. I did not accept your invitation to [https://github.com/TheNode92/pepe-migration](https://github.com/TheNode92/pepe-migration) in time and it expired. Can you please send another one?

**Comment by TheNode92** [comment]
Hi Anton, ty for your message🙂 I just invited you, have a look pls

**Comment by abernatskiy** [comment]
Just accepted it, will check it some time later. Thanks!
